### ISSUE TITLE
Ramsey UUID library is required

### ISSUE THREAD

**Issue by chrisnoden** [somnambulist-tech/api-bundle#5]
I am not able to use this library without also installing the Ramsey\Uuid library. The error is:

> Attempted to load class "Uuid" from namespace "Ramsey\Uuid".
Did you forget a "use" statement for e.g. "Symfony\Component\Validator\Constraints\Uuid" or "Somnambulist\Components\Validation\Rules\Uuid"?

This is happening in `v6.0.1`

**Comment by dave-redfern** [comment]
Resolved in 6.1.0
